# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:          pretty
#relative_permalinks: true

# Setup
title:               Louis
tagline:             'Better than before'
description:         'A personal website about me. Also, sharing technical things I found useful, reading and travels </a>.'
url:                 "https://Louis.github.io" # the base hostname & protocol for your site
#url:               "http://localhost:4000" # use this url when you develope
baseurl:            "Louis.github.io"
paginate:            5


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:     Asia/Taipei
permalink:    /:year-:month-:day/:title/

# About/contact
author:
  name:              Louis
  url:               https://www.instagram.com/liulouis0419/
  email:             qazqazqaz850@gmail.com
  gravatar_md5: 220d6ef27327059400e760067eca1c7b


# Plugin (2018/08/24 Louis)
plugins: [jekyll-paginate]

# Custom vars
version:             1.0.0

theme: jekyll-theme-minimal